//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceConsumer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SumClass", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SumClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FirstField;
        
        private int SecondField;
        
        private int SumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int First {
            get {
                return this.FirstField;
            }
            set {
                if ((this.FirstField.Equals(value) != true)) {
                    this.FirstField = value;
                    this.RaisePropertyChanged("First");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Second {
            get {
                return this.SecondField;
            }
            set {
                if ((this.SecondField.Equals(value) != true)) {
                    this.SecondField = value;
                    this.RaisePropertyChanged("Second");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MyServiceSoap")]
    public interface MyServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumOfNums", ReplyAction="*")]
        int SumOfNums(int First, int Second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumOfNums", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumOfNumsAsync(int First, int Second);
        
        // CODEGEN: Generating message contract since the wrapper name (SumOfDoubles) of message SumOfDoubles does not match the default value (SumOfNums1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumOfDoubles", ReplyAction="*")]
        ServiceConsumer.ServiceReference1.SumOfDoubles1 SumOfNums1(ServiceConsumer.ServiceReference1.SumOfDoubles request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumOfDoubles", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.SumOfDoubles1> SumOfNums1Async(ServiceConsumer.ServiceReference1.SumOfDoubles request);
        
        // CODEGEN: Generating message contract since the wrapper name (SumOfFloats) of message SumOfFloats does not match the default value (SumOfNums2)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumOfFloats", ReplyAction="*")]
        ServiceConsumer.ServiceReference1.SumOfFloats1 SumOfNums2(ServiceConsumer.ServiceReference1.SumOfFloats request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumOfFloats", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.SumOfFloats1> SumOfNums2Async(ServiceConsumer.ServiceReference1.SumOfFloats request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetSumThroughObject) of message GetSumThroughObject does not match the default value (SumOfNumsVTwo)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSumThroughObject", ReplyAction="*")]
        ServiceConsumer.ServiceReference1.GetSumThroughObject1 SumOfNumsVTwo(ServiceConsumer.ServiceReference1.GetSumThroughObject request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSumThroughObject", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.GetSumThroughObject1> SumOfNumsVTwoAsync(ServiceConsumer.ServiceReference1.GetSumThroughObject request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumOfDoubles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumOfDoubles {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double First;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double Second;
        
        public SumOfDoubles() {
        }
        
        public SumOfDoubles(double First, double Second) {
            this.First = First;
            this.Second = Second;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumOfDoublesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumOfDoubles1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double SumOfDoublesResult;
        
        public SumOfDoubles1() {
        }
        
        public SumOfDoubles1(double SumOfDoublesResult) {
            this.SumOfDoublesResult = SumOfDoublesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumOfFloats", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumOfFloats {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float First;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public float Second;
        
        public SumOfFloats() {
        }
        
        public SumOfFloats(float First, float Second) {
            this.First = First;
            this.Second = Second;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumOfFloatsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SumOfFloats1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public float SumOfFloatsResult;
        
        public SumOfFloats1() {
        }
        
        public SumOfFloats1(float SumOfFloatsResult) {
            this.SumOfFloatsResult = SumOfFloatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSumThroughObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSumThroughObject {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string JsonStr;
        
        public GetSumThroughObject() {
        }
        
        public GetSumThroughObject(string JsonStr) {
            this.JsonStr = JsonStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSumThroughObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSumThroughObject1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceConsumer.ServiceReference1.SumClass GetSumThroughObjectResult;
        
        public GetSumThroughObject1() {
        }
        
        public GetSumThroughObject1(ServiceConsumer.ServiceReference1.SumClass GetSumThroughObjectResult) {
            this.GetSumThroughObjectResult = GetSumThroughObjectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceSoapChannel : ServiceConsumer.ServiceReference1.MyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceSoapClient : System.ServiceModel.ClientBase<ServiceConsumer.ServiceReference1.MyServiceSoap>, ServiceConsumer.ServiceReference1.MyServiceSoap {
        
        public MyServiceSoapClient() {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SumOfNums(int First, int Second) {
            return base.Channel.SumOfNums(First, Second);
        }
        
        public System.Threading.Tasks.Task<int> SumOfNumsAsync(int First, int Second) {
            return base.Channel.SumOfNumsAsync(First, Second);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumer.ServiceReference1.SumOfDoubles1 ServiceConsumer.ServiceReference1.MyServiceSoap.SumOfNums1(ServiceConsumer.ServiceReference1.SumOfDoubles request) {
            return base.Channel.SumOfNums1(request);
        }
        
        public double SumOfNums1(double First, double Second) {
            ServiceConsumer.ServiceReference1.SumOfDoubles inValue = new ServiceConsumer.ServiceReference1.SumOfDoubles();
            inValue.First = First;
            inValue.Second = Second;
            ServiceConsumer.ServiceReference1.SumOfDoubles1 retVal = ((ServiceConsumer.ServiceReference1.MyServiceSoap)(this)).SumOfNums1(inValue);
            return retVal.SumOfDoublesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.SumOfDoubles1> ServiceConsumer.ServiceReference1.MyServiceSoap.SumOfNums1Async(ServiceConsumer.ServiceReference1.SumOfDoubles request) {
            return base.Channel.SumOfNums1Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.SumOfDoubles1> SumOfNums1Async(double First, double Second) {
            ServiceConsumer.ServiceReference1.SumOfDoubles inValue = new ServiceConsumer.ServiceReference1.SumOfDoubles();
            inValue.First = First;
            inValue.Second = Second;
            return ((ServiceConsumer.ServiceReference1.MyServiceSoap)(this)).SumOfNums1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumer.ServiceReference1.SumOfFloats1 ServiceConsumer.ServiceReference1.MyServiceSoap.SumOfNums2(ServiceConsumer.ServiceReference1.SumOfFloats request) {
            return base.Channel.SumOfNums2(request);
        }
        
        public float SumOfNums2(float First, float Second) {
            ServiceConsumer.ServiceReference1.SumOfFloats inValue = new ServiceConsumer.ServiceReference1.SumOfFloats();
            inValue.First = First;
            inValue.Second = Second;
            ServiceConsumer.ServiceReference1.SumOfFloats1 retVal = ((ServiceConsumer.ServiceReference1.MyServiceSoap)(this)).SumOfNums2(inValue);
            return retVal.SumOfFloatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.SumOfFloats1> ServiceConsumer.ServiceReference1.MyServiceSoap.SumOfNums2Async(ServiceConsumer.ServiceReference1.SumOfFloats request) {
            return base.Channel.SumOfNums2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.SumOfFloats1> SumOfNums2Async(float First, float Second) {
            ServiceConsumer.ServiceReference1.SumOfFloats inValue = new ServiceConsumer.ServiceReference1.SumOfFloats();
            inValue.First = First;
            inValue.Second = Second;
            return ((ServiceConsumer.ServiceReference1.MyServiceSoap)(this)).SumOfNums2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceConsumer.ServiceReference1.GetSumThroughObject1 ServiceConsumer.ServiceReference1.MyServiceSoap.SumOfNumsVTwo(ServiceConsumer.ServiceReference1.GetSumThroughObject request) {
            return base.Channel.SumOfNumsVTwo(request);
        }
        
        public ServiceConsumer.ServiceReference1.SumClass SumOfNumsVTwo(string JsonStr) {
            ServiceConsumer.ServiceReference1.GetSumThroughObject inValue = new ServiceConsumer.ServiceReference1.GetSumThroughObject();
            inValue.JsonStr = JsonStr;
            ServiceConsumer.ServiceReference1.GetSumThroughObject1 retVal = ((ServiceConsumer.ServiceReference1.MyServiceSoap)(this)).SumOfNumsVTwo(inValue);
            return retVal.GetSumThroughObjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.GetSumThroughObject1> ServiceConsumer.ServiceReference1.MyServiceSoap.SumOfNumsVTwoAsync(ServiceConsumer.ServiceReference1.GetSumThroughObject request) {
            return base.Channel.SumOfNumsVTwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceConsumer.ServiceReference1.GetSumThroughObject1> SumOfNumsVTwoAsync(string JsonStr) {
            ServiceConsumer.ServiceReference1.GetSumThroughObject inValue = new ServiceConsumer.ServiceReference1.GetSumThroughObject();
            inValue.JsonStr = JsonStr;
            return ((ServiceConsumer.ServiceReference1.MyServiceSoap)(this)).SumOfNumsVTwoAsync(inValue);
        }
    }
}
